[build]
publish = "public"
command = "git submodule update -f --init && hugo --gc --minify"


[context.production.environment]
HUGO_VERSION = "0.110.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
HUGO_TITLE = "Memorest"
HUGO_THEME = "PaperMod"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.110.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.110.0"
HUGO_ENV = "preview"
HUGO_ENABLEGITINFO = "true"
HUGO_TITLE = "My PaperMod Preview"
HUGO_THEME = "PaperMod"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.110.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
HUGO_TITLE = "My PaperMod Branch"
HUGO_THEME = "PaperMod"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"